services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROXY_REGISTRY: docker.io
    ports:
      - 8000:8000
    env_file:
      - .env
    volumes:
      - ./:/app
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    restart: always
    env_file:
      - .env
    ports:
      - 6379:6379
